server:
  port: 8081
spring:
  application:
    name: jdbc-mysql-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: ${MAX_POOL_SIZE:100}
management:
  endpoints:
    web:
      exposure:
        include: health, loggers, prometheus
  endpoint:
    loggers.enabled: true
    metrics.enabled: true
    prometheus.enabled: true
    health:
      show-details: always
      probes.enabled: true
